BEGIN EXCLUSIVE;
CREATE TABLE easteregg_flags (easteregg_id INTEGER PRIMARY KEY, flag TEXT UNIQUE NOT NULL, link TEXT NOT NULL, counter INTEGER NOT NULL, creator INTEGER NOT NULL REFERENCES users(id));
COMMIT;
